//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactCenterBL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactCenterBL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table border=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img style=&quot;border:none&quot; src=&quot;cid:obraimagen&quot; /&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///    
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string _base {
            get {
                return ResourceManager.GetString("_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cabecera {
            get {
                object obj = ResourceManager.GetObject("cabecera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cabecera_correo2 {
            get {
                object obj = ResourceManager.GetObject("cabecera_correo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color:white;&quot;&gt;
        ///    &lt;table id=&quot;min-width: 550px; max-width: 550px; width: 550px; font-family: Calibri; margin: 0 auto; border:12px solid red;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;table  style=&quot;width:100%; margin-top:20px&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td style=&quot;width:18%&quot;&gt;&lt;/td&gt;
        ///                        &lt;td style=&quot;width:64%; text-al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html style=&quot;background-color: white;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table id=&quot;container&quot; style=&quot;min-width: 550px; max-width: 550px; width: 550px; font-family: Calibri; margin: 0 auto;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;table  style=&quot;width:100%; margin-top:20px&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td style=&quot;width:18%&quot;&gt;&lt;/td&gt;
        ///                        &lt;td style=&quot;width:64%; text-align: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nuevomail {
            get {
                return ResourceManager.GetString("nuevomail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
